spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sakila_address"
    username: "root"
    password: "fab014"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: true
  cache:
    type: "redis"
  redis:
    port: 6379
    host: "localhost"