spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sakila_address"
    username: "root"
    password: "fab014"
  boot:
    admin:
      client:
        url: "http://localhost:8081"
management:
  endpoints:
    health:
      show-details: "always"
    web:
      exposure:
        include: "*"
    security:
      enabled: false
info:
  app:
    name: @project.name@
    version: @project.version@